name: "Github action build chain. Cross-repo builds"
author: "Enrique Mingorance Cano <emingora@redhat.com>"
description: |
  Github action build chain is a tool to build multiple projects from different repositories in a single action.
inputs:
  definition-file:
    description: "the file where the build chain is defined. It can a file in the same repository (relative path) or a URL"
    required: false
  matrix-variables:
    description: "the map of matrix-variable-key:matrix-variable-value in case you want to use them from build-command/build-command-upstream.."
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "box"
  color: "red"
