on: [pull_request]

jobs:
  build-chain:
    runs-on: ubuntu-latest
    name: Build Pull Request
    steps:
      - uses: actions/checkout@v2
      - name: Build Chain ${{ matrix.java-version }}
        id: build-chain
        uses: ginxo/github-action-build-chain@BXMSPROD-1025
        with:
          definition-file: https://raw.githubusercontent.com/${GROUP}/${PROJECT_NAME}/${BRANCH}/.ci/pull-request-config.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
