on: [pull_request]

jobs:
  build-chain:
    runs-on: ubuntu-latest
    name: Build Pull Request
    steps:
      - uses: actions/checkout@v2
      - name: Build Chain
        id: build-chain
        uses: kiegroup/github-action-build-chain@master
        with:
          parent-dependencies: "lienzo-core"
          child-dependencies: "droolsjbpm-build-bootstrap"
          build-command: "mvn clean install"
          build-command-upstream: "mvn clean"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
